# Generated by Django 2.2.15 on 2020-08-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('birth_year', models.IntegerField(null=True)),
                ('birth_month', models.IntegerField(null=True)),
                ('birth_day', models.IntegerField(null=True)),
                ('birth_country', models.CharField(max_length=255, null=True)),
                ('birth_state', models.CharField(max_length=255, null=True)),
                ('birth_city', models.CharField(max_length=255, null=True)),
                ('death_year', models.IntegerField(null=True)),
                ('death_month', models.IntegerField(null=True)),
                ('death_day', models.IntegerField(null=True)),
                ('death_country', models.CharField(max_length=255, null=True)),
                ('death_state', models.CharField(max_length=255, null=True)),
                ('death_city', models.CharField(max_length=255, null=True)),
                ('name_first', models.CharField(max_length=255, null=True)),
                ('name_last', models.CharField(max_length=255, null=True)),
                ('name_given', models.CharField(max_length=255, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('bats', models.CharField(max_length=255, null=True)),
                ('throws', models.CharField(max_length=255, null=True)),
                ('debut', models.CharField(max_length=255, null=True)),
                ('final_game', models.CharField(max_length=255, null=True)),
                ('retro_id', models.CharField(max_length=255, null=True)),
                ('bbref_id', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField()),
                ('debut_date', models.DateField()),
                ('final_game_date', models.DateField()),
                ('death_date', models.DateField()),
            ],
        ),
    ]
